--- 
development: 
  adapter: postgresql
  database: startupmatchup_development
  encoding: unicode
  password: 
  pool: 5
  username: cbordeleau
test: 
  adapter: postgresql
  database: startupmatchup_test
  encoding: unicode
  password: 
  pool: 5
  username: cbordeleau
